#+TITLE: bryanrinders.xyz
#+SUBTITLE: README
#+AUTHOR: Bryan Rinders
#+DATE: <2023-09-30>
#+OPTIONS: ^:{} toc:nil num:nil todo:t

* My Website
:PROPERTIES:
:CUSTOM_ID: my-website
:END:
The source code for [[https://bryanrinders.xyz]], generated using
[[https://www.gnu.org/software/emacs/manual/html_mono/org.html#Publishing][org-publish]].

- Git repo Gitlab: [[https://gitlab.com/bryanrinders/bryanrinders.xyz]]

  Mirrors:
  - Github: [[https://github.com/BryanRi/bryanrinders.xyz]]

* Build
:PROPERTIES:
:CUSTOM_ID: build
:END:
To generate the website, html pages, css, etc use ~build.sh [OPTION]~.
If =OPTION= is not specified then generate only those files that are
new or that have changed since the last build.

=OPTION= can be:

- d, debug :: starts a new emacs server using the
  =build-site-debug.el= as =init.el=, this will make sure you actual
  =init.el= does not unknowingly mess with the websites configuration.
  =build-site-debug.el= is a very bare bones config using only builtin
  features.
- a, all :: regenerate the entire website. This is useful for example
  when you modify the =nav-bar= in =build-site.el=. So non of the org
  files have changed and therefore running ~./build.sh~ will not
  update any of the html files. You will need to run ~./build.sh all~.

If you use the emacs package [[https://docs.projectile.mx/projectile/index.html][projectile]] than you can generate the
website with =M-x projectile-compile-project=, which calls =build.sh=.
With the prefix argument you can also pass the script arguments.

* TODO Wishlist [2/4]
:PROPERTIES:
:CUSTOM_ID: wishlist-14
:END:
- [ ] Use CATEGORY to automatically make sub-sitemaps. This allows for
  dynamically increasing the number of sitemaps, and hence no need to
  add more and more components to the =org-publish-project-alist=.
- [ ] Add light theme
- [X] Make headline anchors deterministic
- [X] Add usage section to the readme for ~build.sh~

* TODO Fix List
:PROPERTIES:
:CUSTOM_ID: fix-list
:END:
- [X] TOC headline color
- [ ] Color of the number of numbered headings (guix home)
