#+TITLE: Advent Of Cyber 2022 (TryHackMe)
#+AUTOR: Bryan Rinders
#+DATE: 2022-12-06
#+OPTIONS: num:nil

* Day 1 Frameworks
** Puzzle 1
1. Reconnaissance
2. Weaponization
3. Delivery
4. Social Engineering
5. Exploitation
6. Persistence
7. Defence Evasion
8. Command & Control

** Puzzle 2
1. Pivoting
2. Discovery
3. Priviledge Escalation
4. Execution
5. Credential Access
6. Lateral Movement

** Puzzle 3
1. Access
2. Collection
3. Exfiltration
4. Impact
5. Objectivication

** Answers
Who is the adversary that attacked Santa's network this year?

#+BEGIN_SRC example
The Bandit Yeti
#+END_SRC

What's the flag that they left behind?

#+BEGIN_SRC example
THM{IT'S A Y3T1 CHR1$TMA$}
#+END_SRC

* Day 2 Log Analysis
Use the ls command to list the files present in the current directory. How many log files are present?

#+begin_src sh :export both :eval never-export
  ls .*.log* | wc -l
#+end_src

#+RESULTS:
: 2

Elf McSkidy managed to capture the logs generated by the web server. What is the name of this log file?

#+begin_src
  webserver.log
#+end_src

On what day was Santa's naughty and nice list stolen?

#+begin_src sh :export both :eval never-export
  grep "santaslist.txt" webserver.log
#+end_src

#+RESULTS:
: 

* Day 3 OSINT
* Day 4 Scanning
* Day 5 Brute Forcing
Use Hydra to find the VNC password of the target with IP address
*MACHINE_IP*. What is the password?

#+begin_src sh :export both :eval never-export
  hydra -P /usr/share/wordlists/rockyou.txt MACHINE_IP vnc
#+end_src

#+RESULTS:
: 1q2w3e4r

Using a VNC client on the AttackBox, connect to the target of IP
address MACHINE_IP. What is the flag written on the target’s screen?

When using an attackbox open Remmina from Application > Internet >
Remmina. Click cancel when asked to unlock your keyring. Then select
the VNC protocol on the top left corner and type the *MACHINE_IP* in
the search bar. Use the password found in the previous question when
asked for a password. Finally you'll see a screen with the flag.

#+begin_example
THM{I_SEE_YOUR_SCREEN}
#+end_example

* Day 6 Email Analysis
* Day 7 Cyberchef
