#+TITLE: Advent Of Cyber 2022 (TryHackMe)
#+AUTHOR: Bryan Rinders
#+DATE: <2022-12-07 Wed>
#+OPTIONS: num:nil

* Day 1 Frameworks
** Puzzle 1
1. Reconnaissance
2. Weaponization
3. Delivery
4. Social Engineering
5. Exploitation
6. Persistence
7. Defence Evasion
8. Command & Control

** Puzzle 2
1. Pivoting
2. Discovery
3. Priviledge Escalation
4. Execution
5. Credential Access
6. Lateral Movement

** Puzzle 3
1. Access
2. Collection
3. Exfiltration
4. Impact
5. Objectivication

** Answers
Who is the adversary that attacked Santa's network this year?

#+BEGIN_SRC example
The Bandit Yeti
#+END_SRC

What's the flag that they left behind?

#+BEGIN_SRC example
THM{IT'S A Y3T1 CHR1$TMA$}
#+END_SRC

* Day 2 Log Analysis
Use the ls command to list the files present in the current directory. How many log files are present?

#+begin_src sh :export both :eval never-export
  ls *.log | wc -l
#+end_src

#+RESULTS:
: 2

Elf McSkidy managed to capture the logs generated by the web server. What is the name of this log file?

#+begin_src sh :export both :eval never-export
  ls *.log
#+end_src

#+RESULTS:
: webserver.log SSHD.log

On what day was Santa's naughty and nice list stolen?

#+begin_src sh :export both :eval never-export
  grep "santaslist.txt" webserver.log
#+end_src

#+RESULTS:
: 10.10.249.191 - - [18/Nov/2022:12:34:39 +0000] "GET /santaslist.txt HTTP/1.1" 200 133872 "-" "Wget/1.19.4 (linux-gnu)"

November 18 2022 is a Friday.

#+begin_src 
Friday
#+end_src

What is the IP address of the attacker?

From the grep of the previous question the IP is:

#+begin_src 
10.10.249.191
#+end_src

What is the name of the important list that the attacker stole from Santa?

Again from the grep of the previous question the file name is:

#+begin_src
santaslist.txt
#+end_src

Look through the log files for the flag. The format of the flag is: THM{}

#+begin_src sh :export both :eval never-export
  grep THM SSDH.log
#+end_src

#+RESULTS:
: THM{STOLENSANTASLIST}

* Day 3 OSINT
What is the name of the Registrar for the domain santagift.shop?

Go to [[https://who.is/whois/github.com]] and search for =santagift.shop=. The name of the registra is

#+begin_example
NAMECHEAP.INC
#+end_example

Find the website's source code (repository) on github.com and open the file containing sensitive credentials. Can you find the flag?

The url to the source code of the webshop is:

#+begin_example
https://github.com/muhammadthm/SantaGiftShop
#+end_example

Clone the repository and grep for =THM= to easily find the flag.

#+begin_src sh :export both :eval never-export
  git clone https://github.com/muhammadthm/SantaGiftShop.git
  cd SantaGiftShop
  grep 'THM' **/*
#+end_src

#+RESULTS:
: {THM_OSINT_WORKS}

What is the name of the file containing passwords?

#+begin_src sh
  grep password **/*
#+end_src

Among the output you'll find the answer:

#+begin_example
config.php
#+end_example

What is the name of the QA server associated with the website?

#+begin_src sh :eval never-export
  grep QA **/*
#+end_src

Among the output you'll find the url to the QA website:

#+begin_example
qa.santagift.shop
#+end_example

What is the DB_PASSWORD that is being reused between the QA and PROD environments?

#+begin_src sh :eval never-export
  grep 'DB_PASSWORD' **/*
#+end_src

The password is:

#+begin_example
s@nta2022
#+end_example

* Day 4 Scanning
* Day 5 Brute Forcing
Use Hydra to find the VNC password of the target with IP address
*MACHINE_IP*. What is the password?

#+begin_src sh :export both :eval never-export
  hydra -P /usr/share/wordlists/rockyou.txt MACHINE_IP vnc
#+end_src

#+RESULTS:
: 1q2w3e4r

Using a VNC client on the AttackBox, connect to the target of IP
address MACHINE_IP. What is the flag written on the target’s screen?

When using an attackbox open Remmina from Application > Internet >
Remmina. Click cancel when asked to unlock your keyring. Then select
the VNC protocol on the top left corner and type the *MACHINE_IP* in
the search bar. Use the password found in the previous question when
asked for a password. Finally you'll see a screen with the flag.

#+begin_example
THM{I_SEE_YOUR_SCREEN}
#+end_example

* Day 6 Email Analysis
1. What is the email address of the sender?

Open the =Urgent:.eml= with any text editor.
#+begin_src
chief.elf@santaclaus.thm
#+end_src

2. What is the return address?

#+begin_src
murphy.evident@bandityeti.thm
#+end_src

3. On whose behalf was the email sent?

#+begin_src
chief elf
#+end_src

4. What is the X-spam score?

#+begin_src
3
#+end_src

5. What is hidden in the value of the Message-ID field?

Decode the message with a base 64 decoder.
#+begin_src
AoC2022_Email_Analysis
#+end_src

6. Visit the email reputation check website provided in the task. What
   is the reputation result of the sender's email address?

Go to [[https://emailrep.io/]] and search for =chief.elf@santaclaus.thm=
#+begin_src
Risky
#+end_src

7. Check the attachments. What is the filename of the attachment?

#+begin_src
Division_of_labour-Load_share_plan.doc
#+end_src

8. What is the hash value of the attachment?

#+begin_src sh :export both :eval never-export
emlAnalyzer -i Urgent\:.eml --extract-all
cd eml-attachments
sha256sum Division_of_labour-Load_share_plan.doc
#+end_src

#+RESULTS:
: 0827bb9a2e7c0628b82256759f0f888ca1abd6a2d903acdb8e44aca6a1a03467

9. Visit the Virus Total website and use the hash value to
   search. Navigate to the behaviour section. What is the second
   tactic marked in the Mitre ATT&CK section?

Go to [[https://www.virustotal.com/gui/home/upload]] and search for the
hash found in the previous question. Navigate to the behaviour tab and
look for the Mitre section. The second tactic is:
#+begin_src 
defense evasion
#+end_src

10. Visit the InQuest website and use the hash value to search. What
    is the subcategory of the file?

Go to [[https://labs.inquest.net/]] and again search the hash found
previously. Click the full page results. The sub-category is:
#+begin_src 
macro_hunter
#+end_src

* Day 7 Cyberchef
Before answering any of the questions, open firefox and click the
bookmark of cyberchef. Then go through all the 11 steps as explained
in the intro.

What is the version of CyberChef found in the attached VM?

You can find the version number in the url.

#+begin_example
9.49.0
#+end_example

How many recipes were used to extract URLs from the malicious doc?

#+begin_example
10
#+end_example

We found a URL that was downloading a suspicious file; what is the name of that malware?

#+begin_example
mysterygift.exe
#+end_example

What is the last defanged URL of the bandityeti domain found in the last step?

#+begin_example
hxxps[://]cdn[.]bandityeti[.]THM/files/index/
#+end_example

What is the ticket found in one of the domains? (Format: Domain/<GOLDEN_FLAG>)

#+begin_example
THM_MYSTERY_FLAG
#+end_example

* Day 8 Smart Contracts
